%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\Matlab\in_orbit\optical\Attitude.xlsx
%    Worksheet: 计算及复核结果
%
% Auto-generated by MATLAB on 2025-02-09 21:12:20

sheetName = "计算及复核结果";

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A3:P29";

% Specify column names and types
opts.VariableNames = ["UTC", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "UTC1", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16"];
opts.VariableTypes = ["datetime", "string", "string", "double", "string", "double", "categorical", "string", "datetime", "string", "string", "double", "string", "double", "categorical", "string"];

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "VarName3", "VarName5", "VarName8", "VarName10", "VarName11", "VarName13", "VarName16"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "VarName3", "VarName5", "VarName7", "VarName8", "VarName10", "VarName11", "VarName13", "VarName15", "VarName16"], "EmptyFieldRule", "auto");

% Import the data
Attitude = readtable("D:\documents\keyan\projects\Ground-based_Optical-Observation_OD\[20260315]code\toYYJ\Attitude.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts